### ISSUE TITLE
Documentation for GraphConstructor throws error when running

### ISSUE THREAD

**Issue by gwarmstrong** [cameronmartino/TesasSemble#18]
When I run a line like this, 

https://github.com/cameronmartino/TesasSemble/blob/1f7042bf5dc5c2d63e7b85651cc5e54c12afe25b/TesasSemble/preprocessing.py#L85

I get the following error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: fit() missing 1 required positional argument: 'conditions'
```

I think this line should be something like this, from the tests
```python
>>> G_RdBu = GraphConstructor().fit([g1,g2])
```
Or initialize and fit on separate lines

**Comment by cameronmartino** [comment]
@gwarmstrong  yes the following is correct:

```python
>>> G_RdBu = GraphConstructor().fit([g1,g2])
```
