### ISSUE TITLE
These lines mean that the sequences will always be stored by the GraphConstructor object

### ISSUE THREAD

**Issue by gwarmstrong** [cameronmartino/TesasSemble#19]
https://github.com/cameronmartino/TesasSemble/blob/f74eb44b2ad5b43013c12fe444251d332bc1dae1/TesasSemble/preprocessing.py#L116-L125

Can you write a method, something like
```
Parameters
----------
.reindex(data_map)

----------

data_map - dictionary of old_label : new_label  (e.g. {'AGATACA': 1})
```
That relabels the data in each node with value from data_map corresponding to the key for the current node, also relabels the edges to reflect these changes. This will help us cut down on memory used by the graph object

**Comment by gwarmstrong** [comment]
@cameronmartino Actually, it looks like this relabeling is already happening?

**Comment by cameronmartino** [comment]
@gwarmstrong  Yes already labels this way replaces all seqs with an int identifier. You can retrieve the map after running using:


```python 
from TesasSemble.preprocessing import GraphConstructor

g1 = 'tests/data/fastq_test/S0.fastq'
g2 = 'tests/data/fastq_test/S1.fastq'
G_RdBu = GraphConstructor(k=21).fit([g1,g2])
# this is what you are looking for (dict. form)
node_fasta = G_RdBu.node_map()
# graphs with ints in nodes/edges mapped to node_fasta
G_condition1 = G_RdBu.condition_graph(g1)
G_condition2 = G_RdBu.condition_graph(g1)
```
